 directories:

  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire_candidates"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire/erased_75_size_18_freq"
    type: "Image"
    processors:
      - type: "Resize"
        resize_range: [ .75, .75 ]
      - type: "Moire"
        frequency_range: [ 0.18, 0.18 ]
        opacity: .75
        mode: "Erase"


  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire_candidates"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire/erased_75_size_20_freq"
    type: "Image"
    processors:
      - type: "Resize"
        resize_range: [ .75, .75 ]
      - type: "Moire"
        frequency_range: [ 0.2, 0.2 ]
        opacity: .75
        mode: "Erase"

  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire_candidates"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire/erased_75_size_22_freq"
    type: "Image"
    processors:
      - type: "Resize"
        resize_range: [ .75, .75 ]
      - type: "Moire"
        frequency_range: [ 0.22, 0.22 ]
        opacity: .75
        mode: "Erase"

  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire_candidates"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire/normal_75_size_18_freq"
    type: "Image"
    processors:
      - type: "Resize"
        resize_range: [ .75, .75 ]
      - type: "Moire"
        frequency_range: [ 0.18, 0.18 ]
        opacity: .75
        mode: "Normal"

  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire_candidates"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire/normal_75_size_20_freq"
    type: "Image"
    processors:
      - type: "Resize"
        resize_range: [.75, .75]
      - type: "Moire"
        frequency_range: [ 0.2, 0.2 ]
        opacity: .75
        mode: "Normal"

  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire_candidates"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire/normal_75_size_22_freq"
    type: "Image"
    processors:
      - type: "Resize"
        resize_range: [ .75, .75 ]
      - type: "Moire"
        frequency_range: [ 0.22, 0.22 ]
        opacity: .75
        mode: "Normal"

  # Resize to 75 for ground truth
  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire_candidates"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/moire/75_resize"
    type: "Image"
    processors:
      - type: "Resize"
        resize_range: [ .75, .75 ]