directories:

  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-images/raw"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-images/moire/75_size_15_freq"
    type: "SinglePage"
    processors:
      - type: "Resize"
        resize_range: [.75, .75]
      - type: "Moire"
        frequency_range: [ 0.2, 0.2 ]
        opacity: 1

#  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-images/raw"
#    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-images/moire/75_size_20_freq"
#    type: "SinglePage"
#    processors:
#      - type: "Resize"
#        resize_range: [.75, .75]
#      - type: "Moire"
#        frequency_range: [ 0.2, 0.2 ]
#        opacity: 1
#
#  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-images/raw"
#    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-images/moire/75_size_30_freq_75_opacity"
#    type: "SinglePage"
#    processors:
#      - type: "Resize"
#        resize_range: [ .75, .75 ]
#      - type: "Moire"
#        frequency_range: [ 0.3, 0.3 ]
#        opacity: .75



