directories:
  - input_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/filtered"
    output_dir: "/Users/iankonradjohnson/base/abacus/data/archive-pdfs/aug"
    type: "Image"
    copies: 3
    processors:
      - type: "ImageAugmentor"
