directories:
  - input_dir: "/Users/iankonradjohnson/base/abacus/BookProjects/Colonial_Interiors/test/input"
    output_dir: "/Users/iankonradjohnson/base/abacus/BookProjects/Colonial_Interiors/test/input_blur"
    type: "Image"
    processors:
      - type: "GaussianBlur"
