directories:
  - input_dir: "/Users/iankonradjohnson/Downloads/test/in"
    output_dir: "/Users/iankonradjohnson/Downloads/test/out"
    type: "SinglePage"
    processors:
      - type: "GreyscaleBinarySeparator"
        # Detection configuration
        detection:
          # Region extraction settings - much less sensitive to grayscale content
          region_extraction:
            threshold: 0.5             # Much higher threshold for minimal sensitivity
            min_region_size: 5000      # Much larger minimum size to only detect major regions
            expand_pixels: 2           # Minimal expansion to avoid including binary content
            fill_holes: true           # Fill holes in regions

        # Processing configuration
        processing:
          # Binary region processing settings
          binary:
            threshold: 128             # Threshold value (0-255, null for auto)
            invert: false              # Whether to invert the result

          # Grayscale region processing settings
          grayscale:
            brightness: 0.1            # Slight brightness boost
            contrast: 1.2              # Moderate contrast boost
            dpi: 300                   # Target DPI
            dither_type: none          # Preserve grayscale values instead of dithering
            preserve_grayscale: true   # Keep grayscale values
            threshold: null            # Threshold value (null for auto)

        # Visualization settings for debugging
        save_visualization: true       # Enable visualizations
        visualization_path: "/Users/iankonradjohnson/base/abacus/BatchImageProcessor/output"

