directories:
  - input_dir: "/Users/iankonradjohnson/base/abacus/BookProjects/TheModelArchitect/Volume1/images/deskewed/binary_out"
    output_dir: "/Users/iankonradjohnson/base/abacus/BookProjects/TheModelArchitect/Volume1/images/deskewed/binary_out_downsampled"
    type: "SinglePage"
    processors:
      - type: "Resize"
        resize_range: [0.4, 0.4]
