directories:
  - input_dir: "/Users/iankonradjohnson/base/abacus/BookProjects/CountryHouseLibrary/ArchitecturalStylesForCountryHouses/tailored-upscaled/text"
    output_dir: "/Users/iankonradjohnson/base/abacus/BookProjects/CountryHouseLibrary/ArchitecturalStylesForCountryHouses/tailored-upscaled-postprocess/text"
    type: "Image"
    processors:
      - type: "Threshold"
        threshold_value: 185
      - type: "ImageModeConverter"
        mode: "1"
